- hosts: ansible-practic

  tasks:
    # создаем пользователя ansible-worker
    - name: create ansible-worker user
      ansible.builtin.user:
        name: ansible-worker
        state: present
        shell: /bin/bash
        groups: www-data
      become: yes
      tags: build_user
    
    # настройка для группы ansible-worker
    - name: setting for ansible-worker
      ansible.builtin.file:
        path: /home/ansible-worker
        owner: www-data
        group: ansible-worker
      become: yes
      tags: build_user