- hosts: ansible-practic
  gather_facts: no

  tasks: 
    # установка git 
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: git_init

    # копируем приватный ssh ключ для работы с гитом
    - name: copy id_rsa и id_rsa.pub
      ansible.builtin.copy:
        src: ../ssh_keys/id_rsa
        dest: "~/.ssh/id_rsa"
        mode: '0600'
      become: yes
      tags: git_init

    # копируем публичный ssh ключ для работы с гитом
    - name: copy id_rsa и id_rsa.pub
      ansible.builtin.copy:
        src: "../ssh_keys/id_rsa.pub"
        dest: "~/.ssh/id_rsa.pub"
        mode: '0644'
      become: yes
      tags: git_init
