- hosts: ansible-practic
  gather_facts: no

  tasks: 
    # изменение данных в /home/ansible-worker/www/stud-template/index.html
    - name: change data in index.html
      ansible.builtin.copy:
        src: ../files/index.html
        dest: /home/ansible-worker/www/stud-template/index.html
        mode: '0644'
      become: yes
      tags: build_repo