- hosts: webserver
  remote_user: ubuntu
  gather_facts: no
  vars:
    users:
      - { name: jaime, email: jaime@test.com }
      - { name: sansa, email: sansa@test.com }
      - { name: robert, email: robert@test.com }

  tasks:
    - name: create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        group: ubuntu
      loop: "{{ users }}"
      become: yes

    # - name: create directory .ssh
    #   ansible.builtin.file:
    #     path: "/home/{{ item.name }}/.ssh"
    #     state: directory
    #   loop: "{{ users }}"
    #   become: yes

    - name: create authorized_key
      ansible.posix.authorized_key:
        user: "{{item.name}}"
        state: "present"
        key: "{{lookup('file', '../files/ssh_pub.txt')}}"
      loop: "{{ users }}"
      become: yes
